project:
  type: website
  output-dir: "sitewebracine/Quarto/saison22/SaisonReg"

website:
  title: "GEH Statcan"
  navbar:
    left:
      - href: index.qmd
        text: "Calendrier"
      - href: classement.qmd
        text: "Classement"
      - href: compteurs.qmd
        text: "Compteurs"
      - href: documentation.qmd
        text: "Documentation"
      - href: saisonPrécédentes.qmd
        text: "Saisons Précédentes"
      - href: apropos.qmd
        text: "À propos"
format:
  html:
    theme: Lumen
    css: styles.css
    toc: false
    grid:
      sidebar-width: 20px
      body-width: 20000px
      margin-width: 20px
      gutter-width: 1.5rem    

editor: visual


