project:
  type: website
  output-dir: "sitewebracine/saison24"

website:
  title: "GEH Statcan"
  navbar:
    left:
      - href: p0calendrier.qmd
        text: "Calendrier"
      - href: p2classement.qmd
        text: "Classement"
      - href: p3compteurs.qmd
        text: "Compteurs"
      - href: p7arbreseries.qmd
        text: "Arbre des séries"
      - href: p6calendrierseries.qmd
        text: "Calendrier-séries"
      - href: p8compteursseries.qmd
        text: "Compteurs-séries"        
      - href: p4documentation.qmd
        text: "Documentation"
      - href: p5saisonPrécédentes.qmd
        text: "Saisons Précédentes"
      - href: p9apropos.qmd
        text: "À propos"

format:
  html:
    theme: Lumen
    css: styles.css
    toc: false
    grid:
      sidebar-width: 20px
      body-width: 20000px
      margin-width: 20px
      gutter-width: 1.5rem    

editor: visual



