---
title: "instructions"
---

Mise à jours des pages

-   pull de [github](https://github.com/gehstatcan/gehstatcan.github.io) (<https://github.com/gehstatcan/gehstatcan.github.io>)

-   Il faut les fichiers CSV suivant dans C:/GIT/gehstatcan.github.io

    -   tblParties.csv

    -   tblÉquipes.csv

    -   tblJoueurs.csv

    -   tblRépondantsParJoueurs

-   Ajouter les points de la partie dans tblRépondantsParJoueurs. Habituellement 10 lignes. Le fichier Saisie des points.xlsx (Excel 365 seulement) peut aider pour cette tâche .

-   pull de <https://github.com/gehstatcan/CreationPageWeb>

-   Ouvrir le projet R **GEHStatcanQMD.Rproj**

-   faire un "Render" du site. menu Build\|Render Web s

-   Copier le contenu de \\sitewebracine\\Saison22\\SaisonReg vers C:\\GIT\\gehstatcan.github.io\\Saison22\\SaisonReg

-   

-   Envoyer les fichiers du répertoire output-dir: dans le fichier \_quarto.yml vers <https://github.com/gehstatcan/gehstatcan.github.io> ("sitewebracine/Quarto/saison22/SaisonReg")

    -   Moi, j'utilise GitKraken, donc, je copie de output-dir vers mon répertoire lié à GitKraken

Note: Je veux revoir la structure des répertoire. Par exemple, ce fichier devrait être dans "racine/documentation" et non "/Saison22"!

Note: Il n'y a plus de base de données access. Les tables ont été converties en fichier CSV.

4 CSV requis:

-   tblÉquipes.csv

-   tblJoueurs.csv

-   tblParties.csv

-   tblRépondantsParJoueurs.csv