---
title: "Procès-verbaux"
---

***Membre du Comité décisionnel***

-   Julien Bérard-Chagnon, Julie Bernier, Sébastien Landry, Stéphane Mongeau, Geneviève Ouellet, Pierre Parent, Sylvain Perron, Martin Sirois

**Réunion #1: 29 septembre 2005, JT 11 D à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202005-09-29.doc)**

**Réunion #2: 20 juin 2006, JT 11 E à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202006-06-20.doc)**

**Réunion #3: 27 juin 2007, JT 11 D à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202007-06-27.doc)**

**Réunion #4: 9 juillet 2008, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202008-07-09.doc)**

**Réunion #5: 8 juillet 2009, RHC 11-4 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202009-07-08.doc)**

**Réunion #6: 30 juin 2010, RHC 11-4 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202010-06-30.doc)**

**Réunion #7: 29 juin 2011, RHC 11-4 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202011-06-29.docx)**

**Réunion #8: 21 juin 2012, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202012-06-21.docx)**

**Réunion #9: 15 mai 2013, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202013-05-15.docx)**

**Réunion #10: 28 mai 2014, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202014-05-28.docx)**

**Réunion #11: 28 mai 2015, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202015-05-28.docx)**

**Réunion #12: 18 mai 2016, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202016-05-18.docx)**

**Réunion #13: 30 août 2017, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202017-08-30.docx)**

**Réunion #14: 30 mai 2018, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202018-05-30.docx)**

**Réunion #15: 12 juin 2019, RHC 16-3 à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202019-06-12.docx)**

**Réunion #16: 13 janvier 2021, MS Teams à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202021-01-13.docx)**

**Réunion #17: 25 août 2021, MS Teams à midi - [Procès-verbal](https://gehstatcan.github.io/Documentation/Procès%20verbal%202021-08-25.docx)**

**Réunion #18: septembre 2024, MS Teams à midi - n/a**
